### ISSUE TITLE
soap RPC return error message.

### ISSUE THREAD

**Issue by kvzhuang** [rexhome7326/async-fetch-helper#2]
soapClient[methodName](params, function soapClientCallback(clientError, clientResponce) {
	let result = {};

	if(clientResponce && clientResponce.hasOwnProperty('return')){
		try {
			result = JSON.parse(clientResponce.return);	
		} catch(err) {
			result = clientResponce.return;
		}
		
	}
	if (clientError !== null) {
		result = clientError.body;
	}

**Comment by rexhome7326** [comment]
fixed
